create sequence eventos_venta_id_seq;

alter sequence eventos_venta_id_seq owner to postgres;

create sequence eventos_itemventa_id_seq;

alter sequence eventos_itemventa_id_seq owner to postgres;

create table django_migrations
(
    id      bigint generated by default as identity
        primary key,
    app     varchar(255)             not null,
    name    varchar(255)             not null,
    applied timestamp with time zone not null
);

alter table django_migrations
    owner to postgres;

create table parameters_mediopago
(
    id     bigint generated by default as identity
        primary key,
    nombre varchar(50) not null
);

alter table parameters_mediopago
    owner to postgres;

create table parameters_pais
(
    id     bigint generated by default as identity
        primary key,
    nombre varchar(100) not null
        unique
);

alter table parameters_pais
    owner to postgres;

create index parameters_pais_nombre_415c07c0_like
    on parameters_pais (nombre varchar_pattern_ops);

create table parameters_parentesco
(
    id               bigint generated by default as identity
        primary key,
    nombre           varchar(50) not null,
    menor_al_titular boolean     not null
);

alter table parameters_parentesco
    owner to postgres;

create table parameters_sexo
(
    id     bigint generated by default as identity
        primary key,
    nombre varchar(100) not null
        unique
);

alter table parameters_sexo
    owner to postgres;

create index parameters_sexo_nombre_d7965317_like
    on parameters_sexo (nombre varchar_pattern_ops);

create table parameters_provincia
(
    id      bigint generated by default as identity
        primary key,
    nombre  varchar(100) not null,
    pais_id bigint       not null
        constraint parameters_provincia_pais_id_78d33041_fk_parameters_pais_id
            references parameters_pais
            deferrable initially deferred,
    constraint parameters_provincia_nombre_pais_id_6d15e2c7_uniq
        unique (nombre, pais_id)
);

alter table parameters_provincia
    owner to postgres;

create index parameters_provincia_pais_id_78d33041
    on parameters_provincia (pais_id);

create table parameters_municipio
(
    id           bigint generated by default as identity
        primary key,
    nombre       varchar(255) not null,
    provincia_id bigint       not null
        constraint parameters_municipio_provincia_id_38ea42f1_fk_parameter
            references parameters_provincia
            deferrable initially deferred
);

alter table parameters_municipio
    owner to postgres;

create index parameters_municipio_provincia_id_38ea42f1
    on parameters_municipio (provincia_id);

create table parameters_departamento
(
    id           bigint generated by default as identity
        primary key,
    nombre       varchar(100) not null,
    provincia_id bigint       not null
        constraint parameters_departame_provincia_id_638d2485_fk_parameter
            references parameters_provincia
            deferrable initially deferred,
    constraint parameters_departamento_nombre_provincia_id_eba656b4_uniq
        unique (nombre, provincia_id)
);

alter table parameters_departamento
    owner to postgres;

create index parameters_departamento_provincia_id_638d2485
    on parameters_departamento (provincia_id);

create table parameters_localidad
(
    id              bigint generated by default as identity
        primary key,
    nombre          varchar(255) not null,
    categoria       varchar(50)  not null,
    departamento_id bigint
        constraint parameters_localidad_departamento_id_04496de2_fk_parameter
            references parameters_departamento
            deferrable initially deferred,
    municipio_id    bigint
        constraint parameters_localidad_municipio_id_b3fe6d1c_fk_parameter
            references parameters_municipio
            deferrable initially deferred,
    provincia_id    bigint       not null
        constraint parameters_localidad_provincia_id_1afa63e4_fk_parameter
            references parameters_provincia
            deferrable initially deferred,
    constraint parameters_localidad_nombre_provincia_id_depa_5088e571_uniq
        unique (nombre, provincia_id, departamento_id, municipio_id)
);

alter table parameters_localidad
    owner to postgres;

create table core_club
(
    id           bigint generated by default as identity
        primary key,
    is_deleted   boolean      not null,
    deleted_at   timestamp with time zone,
    nombre       varchar(255) not null,
    direccion    varchar(255) not null,
    email        varchar(255) not null,
    imagen       varchar(100),
    localidad_id bigint       not null
        constraint core_club_localidad_id_b58ddc9c_fk_parameters_localidad_id
            references parameters_localidad
            deferrable initially deferred,
    constraint core_club_localidad_id_direccion_63a3674e_uniq
        unique (localidad_id, direccion)
);

alter table core_club
    owner to postgres;

create index core_club_localidad_id_b58ddc9c
    on core_club (localidad_id);

create index parameters_localidad_departamento_id_04496de2
    on parameters_localidad (departamento_id);

create index parameters_localidad_municipio_id_b3fe6d1c
    on parameters_localidad (municipio_id);

create index parameters_localidad_provincia_id_1afa63e4
    on parameters_localidad (provincia_id);

create table django_content_type
(
    id        integer generated by default as identity
        primary key,
    app_label varchar(100) not null,
    model     varchar(100) not null,
    constraint django_content_type_app_label_model_76bd3d3b_uniq
        unique (app_label, model)
);

alter table django_content_type
    owner to postgres;

create table auth_permission
(
    id              integer generated by default as identity
        primary key,
    name            varchar(255) not null,
    content_type_id integer      not null
        constraint auth_permission_content_type_id_2f476e4b_fk_django_co
            references django_content_type
            deferrable initially deferred,
    codename        varchar(100) not null,
    constraint auth_permission_content_type_id_codename_01ab375a_uniq
        unique (content_type_id, codename)
);

alter table auth_permission
    owner to postgres;

create index auth_permission_content_type_id_2f476e4b
    on auth_permission (content_type_id);

create table auth_group
(
    id   integer generated by default as identity
        primary key,
    name varchar(150) not null
        unique
);

alter table auth_group
    owner to postgres;

create index auth_group_name_a6ea08ec_like
    on auth_group (name varchar_pattern_ops);

create table auth_group_permissions
(
    id            bigint generated by default as identity
        primary key,
    group_id      integer not null
        constraint auth_group_permissions_group_id_b120cbf9_fk_auth_group_id
            references auth_group
            deferrable initially deferred,
    permission_id integer not null
        constraint auth_group_permissio_permission_id_84c5c92e_fk_auth_perm
            references auth_permission
            deferrable initially deferred,
    constraint auth_group_permissions_group_id_permission_id_0cd325b0_uniq
        unique (group_id, permission_id)
);

alter table auth_group_permissions
    owner to postgres;

create index auth_group_permissions_group_id_b120cbf9
    on auth_group_permissions (group_id);

create index auth_group_permissions_permission_id_84c5c92e
    on auth_group_permissions (permission_id);

create table accounts_user
(
    id             bigint generated by default as identity
        primary key,
    password       varchar(128)             not null,
    last_login     timestamp with time zone,
    is_superuser   boolean                  not null,
    is_staff       boolean                  not null,
    is_active      boolean                  not null,
    date_joined    timestamp with time zone not null,
    email          varchar(254)             not null
        unique,
    nombre         varchar(255)             not null,
    apellido       varchar(255)             not null,
    notificaciones boolean                  not null
);

alter table accounts_user
    owner to postgres;

create index accounts_user_email_b2644a56_like
    on accounts_user (email varchar_pattern_ops);

create table accounts_historicalpersona
(
    id                    bigint                   not null,
    is_deleted            boolean                  not null,
    deleted_at            timestamp with time zone,
    cuil                  varchar(11)              not null,
    nombre                varchar(255)             not null,
    apellido              varchar(255)             not null,
    fecha_nacimiento      date                     not null,
    imagen                text                     not null,
    history_id            integer generated by default as identity
        primary key,
    history_date          timestamp with time zone not null,
    history_change_reason varchar(100),
    history_type          varchar(1)               not null,
    club_id               bigint,
    history_user_id       bigint
        constraint accounts_historicalp_history_user_id_31d79eec_fk_accounts_
            references accounts_user
            deferrable initially deferred,
    persona_titular_id    bigint,
    sexo_id               bigint
);

alter table accounts_historicalpersona
    owner to postgres;

create index accounts_historicalpersona_id_67f0a9ab
    on accounts_historicalpersona (id);

create index accounts_historicalpersona_cuil_85dd6b36
    on accounts_historicalpersona (cuil);

create index accounts_historicalpersona_cuil_85dd6b36_like
    on accounts_historicalpersona (cuil varchar_pattern_ops);

create index accounts_historicalpersona_history_date_d5fe26a2
    on accounts_historicalpersona (history_date);

create index accounts_historicalpersona_club_id_6b159b11
    on accounts_historicalpersona (club_id);

create index accounts_historicalpersona_history_user_id_31d79eec
    on accounts_historicalpersona (history_user_id);

create index accounts_historicalpersona_persona_titular_id_2e57e232
    on accounts_historicalpersona (persona_titular_id);

create index accounts_historicalpersona_sexo_id_ab5390ea
    on accounts_historicalpersona (sexo_id);

create table accounts_persona
(
    id                 bigint generated by default as identity
        primary key,
    is_deleted         boolean      not null,
    deleted_at         timestamp with time zone,
    cuil               varchar(11)  not null
        unique
        constraint cuil_valido
            check ((cuil)::text ~ '^[0-9]{11}$'::text),
    nombre             varchar(255) not null
        constraint persona_nombre_valido
            check ((nombre)::text ~ '^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$'::text),
    apellido           varchar(255) not null
        constraint persona_apellido_valido
            check ((apellido)::text ~ '^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$'::text),
    fecha_nacimiento   date         not null,
    imagen             varchar(100) not null,
    club_id            bigint       not null
        constraint accounts_persona_club_id_ec4eac98_fk_core_club_id
            references core_club
            deferrable initially deferred,
    persona_titular_id bigint
        constraint accounts_persona_persona_titular_id_cdf074ba_fk_accounts_
            references accounts_persona
            deferrable initially deferred,
    sexo_id            bigint       not null
        constraint accounts_persona_sexo_id_17884256_fk_parameters_sexo_id
            references parameters_sexo
            deferrable initially deferred,
    constraint persona_titular_distinta
        check ((persona_titular_id IS NULL) OR (NOT ((persona_titular_id = id) AND (persona_titular_id IS NOT NULL))))
);

alter table accounts_persona
    owner to postgres;

create index accounts_persona_cuil_1d63f23c_like
    on accounts_persona (cuil varchar_pattern_ops);

create index accounts_persona_club_id_ec4eac98
    on accounts_persona (club_id);

create index accounts_persona_persona_titular_id_cdf074ba
    on accounts_persona (persona_titular_id);

create index accounts_persona_sexo_id_17884256
    on accounts_persona (sexo_id);

create table accounts_user_groups
(
    id       bigint generated by default as identity
        primary key,
    user_id  bigint  not null
        constraint accounts_user_groups_user_id_52b62117_fk_accounts_user_id
            references accounts_user
            deferrable initially deferred,
    group_id integer not null
        constraint accounts_user_groups_group_id_bd11a704_fk_auth_group_id
            references auth_group
            deferrable initially deferred,
    constraint accounts_user_groups_user_id_group_id_59c0b32f_uniq
        unique (user_id, group_id)
);

alter table accounts_user_groups
    owner to postgres;

create index accounts_user_groups_user_id_52b62117
    on accounts_user_groups (user_id);

create index accounts_user_groups_group_id_bd11a704
    on accounts_user_groups (group_id);

create table accounts_user_user_permissions
(
    id            bigint generated by default as identity
        primary key,
    user_id       bigint  not null
        constraint accounts_user_user_p_user_id_e4f0a161_fk_accounts_
            references accounts_user
            deferrable initially deferred,
    permission_id integer not null
        constraint accounts_user_user_p_permission_id_113bb443_fk_auth_perm
            references auth_permission
            deferrable initially deferred,
    constraint accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq
        unique (user_id, permission_id)
);

alter table accounts_user_user_permissions
    owner to postgres;

create index accounts_user_user_permissions_user_id_e4f0a161
    on accounts_user_user_permissions (user_id);

create index accounts_user_user_permissions_permission_id_113bb443
    on accounts_user_user_permissions (permission_id);

create table django_admin_log
(
    id              integer generated by default as identity
        primary key,
    action_time     timestamp with time zone not null,
    object_id       text,
    object_repr     varchar(200)             not null,
    action_flag     smallint                 not null
        constraint django_admin_log_action_flag_check
            check (action_flag >= 0),
    change_message  text                     not null,
    content_type_id integer
        constraint django_admin_log_content_type_id_c4bce8eb_fk_django_co
            references django_content_type
            deferrable initially deferred,
    user_id         bigint                   not null
        constraint django_admin_log_user_id_c564eba6_fk_accounts_user_id
            references accounts_user
            deferrable initially deferred
);

alter table django_admin_log
    owner to postgres;

create index django_admin_log_content_type_id_c4bce8eb
    on django_admin_log (content_type_id);

create index django_admin_log_user_id_c564eba6
    on django_admin_log (user_id);

create table django_apscheduler_djangojob
(
    id            varchar(255) not null
        primary key,
    next_run_time timestamp with time zone,
    job_state     bytea        not null
);

alter table django_apscheduler_djangojob
    owner to postgres;

create index django_apscheduler_djangojob_next_run_time_2f022619
    on django_apscheduler_djangojob (next_run_time);

create table django_apscheduler_djangojobexecution
(
    id        bigint generated by default as identity
        primary key,
    status    varchar(50)              not null,
    run_time  timestamp with time zone not null,
    duration  numeric(15, 2),
    finished  numeric(15, 2),
    exception varchar(1000),
    traceback text,
    job_id    varchar(255)             not null
        constraint django_apscheduler_djangojobexecution_job_id_daf5090a_fk
            references django_apscheduler_djangojob
            deferrable initially deferred,
    constraint unique_job_executions
        unique (job_id, run_time)
);

alter table django_apscheduler_djangojobexecution
    owner to postgres;

create index django_apscheduler_djangojobexecution_run_time_16edd96b
    on django_apscheduler_djangojobexecution (run_time);

create index django_apscheduler_djangojobexecution_job_id_daf5090a
    on django_apscheduler_djangojobexecution (job_id);

create table eventos_evento
(
    id                bigint generated by default as identity
        primary key,
    is_deleted        boolean                  not null,
    deleted_at        timestamp with time zone,
    nombre            varchar(255)             not null,
    descripcion       text                     not null,
    fecha_inicio      date                     not null,
    hora_inicio       time                     not null,
    fecha_fin         date                     not null,
    hora_fin          time                     not null,
    registro_deadline date,
    mayor_edad        boolean                  not null,
    date_created      timestamp with time zone not null,
    date_updated      timestamp with time zone not null,
    imagen            varchar(100)             not null,
    constraint fecha_inicio_menor_fecha_fin
        check (fecha_inicio <= fecha_fin)
);

alter table eventos_evento
    owner to postgres;

create table eventos_ventaticket
(
    id            bigint generated by default as identity
        constraint eventos_venta_pkey
            primary key,
    is_deleted    boolean                  not null,
    deleted_at    timestamp with time zone,
    total         numeric(10, 2)           not null,
    pagado        boolean                  not null,
    preference_id varchar(255),
    date_created  timestamp with time zone not null,
    date_updated  timestamp with time zone not null,
    email         varchar(254)             not null,
    evento_id     bigint                   not null
        constraint eventos_ventaticket_evento_id_8b3d63b0_fk_eventos_evento_id
            references eventos_evento
            deferrable initially deferred
);

alter table eventos_ventaticket
    owner to postgres;

alter sequence eventos_venta_id_seq owned by eventos_ventaticket.id;

create index eventos_ventaticket_evento_id_8b3d63b0
    on eventos_ventaticket (evento_id);

create table eventos_ticketvariante
(
    id            bigint generated by default as identity
        primary key,
    is_deleted    boolean                  not null,
    deleted_at    timestamp with time zone,
    nombre        varchar(255)             not null,
    precio        numeric(10, 2)           not null,
    total_tickets integer                  not null
        constraint eventos_ticketvariante_total_tickets_check
            check (total_tickets >= 0),
    date_created  timestamp with time zone not null,
    date_updated  timestamp with time zone not null,
    evento_id     bigint                   not null
        constraint eventos_ticketvariante_evento_id_99ca8bc8_fk_eventos_evento_id
            references eventos_evento
            deferrable initially deferred
);

alter table eventos_ticketvariante
    owner to postgres;

create index eventos_ticketvariante_evento_id_99ca8bc8
    on eventos_ticketvariante (evento_id);

create table eventos_ticket
(
    id                 bigint generated by default as identity
        primary key,
    is_deleted         boolean                  not null,
    deleted_at         timestamp with time zone,
    nombre             varchar(255)             not null,
    is_used            boolean                  not null,
    date_created       timestamp with time zone not null,
    date_updated       timestamp with time zone not null,
    ticket_variante_id bigint                   not null
        constraint eventos_ticket_ticket_variante_id_a16b87c3_fk_eventos_t
            references eventos_ticketvariante
            deferrable initially deferred,
    venta_ticket_id    bigint                   not null
        constraint eventos_ticket_venta_ticket_id_17357a84_fk_eventos_v
            references eventos_ventaticket
            deferrable initially deferred,
    check_by_id        bigint
        constraint eventos_ticket_check_by_id_b5ba6710_fk_accounts_user_id
            references accounts_user
            deferrable initially deferred,
    check_date         timestamp with time zone,
    constraint ticket_check_date_not_null_if_is_used_is_true
        check ((NOT is_used) OR (check_date IS NOT NULL)),
    constraint ticket_check_by_not_null_if_is_used_is_true
        check ((NOT is_used) OR (check_by_id IS NOT NULL))
);

alter table eventos_ticket
    owner to postgres;

create index eventos_ticket_ticket_variante_id_a16b87c3
    on eventos_ticket (ticket_variante_id);

create index eventos_ticket_venta_id_5202244b
    on eventos_ticket (venta_ticket_id);

create index eventos_ticket_scan_by_id_7c6e84ae
    on eventos_ticket (check_by_id);

create table eventos_itemventaticket
(
    id                 bigint generated by default as identity
        constraint eventos_itemventa_pkey
            primary key,
    cantidad           integer        not null
        constraint eventos_itemventa_cantidad_check
            check (cantidad >= 0),
    subtotal           numeric(10, 2) not null,
    ticket_variante_id bigint         not null
        constraint eventos_itemventa_ticket_variante_id_62356186_fk_eventos_t
            references eventos_ticketvariante
            deferrable initially deferred,
    venta_ticket_id    bigint         not null
        constraint eventos_itemventatic_venta_ticket_id_b36e77f8_fk_eventos_v
            references eventos_ventaticket
            deferrable initially deferred
);

alter table eventos_itemventaticket
    owner to postgres;

alter sequence eventos_itemventa_id_seq owned by eventos_itemventaticket.id;

create index eventos_itemventa_ticket_variante_id_62356186
    on eventos_itemventaticket (ticket_variante_id);

create index eventos_itemventa_venta_ticket_id_2e30c49e
    on eventos_itemventaticket (venta_ticket_id);

create table reservas_horalaboral
(
    id      bigint generated by default as identity
        primary key,
    hora    time   not null,
    club_id bigint not null
        constraint reservas_horalaboral_club_id_d47dc88a_fk_core_club_id
            references core_club
            deferrable initially deferred,
    constraint reservas_horalaboral_club_id_hora_707e7dc2_uniq
        unique (club_id, hora)
);

alter table reservas_horalaboral
    owner to postgres;

create index reservas_horalaboral_club_id_d47dc88a
    on reservas_horalaboral (club_id);

create table reservas_historicalreserva
(
    is_deleted            boolean                  not null,
    deleted_at            timestamp with time zone,
    id                    uuid                     not null,
    nombre                varchar(50)              not null,
    email                 varchar(254)             not null,
    fecha                 date                     not null,
    hora                  time                     not null,
    nota                  text,
    precio                numeric(10, 2)           not null,
    con_luz               boolean                  not null,
    expira                boolean                  not null,
    forma_pago            smallint                 not null
        constraint reservas_historicalreserva_forma_pago_check
            check (forma_pago >= 0),
    pagado                boolean                  not null,
    preference_id         varchar(255),
    asistencia            boolean                  not null,
    created_at            timestamp with time zone not null,
    updated_at            timestamp with time zone not null,
    history_id            integer generated by default as identity
        primary key,
    history_date          timestamp with time zone not null,
    history_change_reason varchar(100),
    history_type          varchar(1)               not null,
    cancha_id             bigint,
    history_user_id       bigint
        constraint reservas_historicalr_history_user_id_eca599bd_fk_accounts_
            references accounts_user
            deferrable initially deferred
);

alter table reservas_historicalreserva
    owner to postgres;

create index reservas_historicalreserva_id_e42e272b
    on reservas_historicalreserva (id);

create index reservas_historicalreserva_history_date_5a6a472b
    on reservas_historicalreserva (history_date);

create index reservas_historicalreserva_cancha_id_b41c5b5c
    on reservas_historicalreserva (cancha_id);

create index reservas_historicalreserva_history_user_id_eca599bd
    on reservas_historicalreserva (history_user_id);

create table reservas_deporte
(
    id     bigint generated by default as identity
        primary key,
    nombre varchar(100) not null
        unique
);

alter table reservas_deporte
    owner to postgres;

create index reservas_deporte_nombre_0e131d44_like
    on reservas_deporte (nombre varchar_pattern_ops);

create table reservas_superficie
(
    id     bigint generated by default as identity
        primary key,
    nombre varchar(100) not null
        unique
);

alter table reservas_superficie
    owner to postgres;

create table reservas_cancha
(
    id                 bigint generated by default as identity
        primary key,
    is_deleted         boolean       not null,
    deleted_at         timestamp with time zone,
    cantidad_jugadores smallint
        constraint reservas_cancha_cantidad_jugadores_check
            check (cantidad_jugadores >= 0),
    precio             numeric(6, 2) not null,
    precio_luz         numeric(6, 2),
    imagen             varchar(100),
    club_id            bigint        not null
        constraint reservas_cancha_club_id_faf63c6d_fk_core_club_id
            references core_club
            deferrable initially deferred,
    deporte_id         bigint        not null
        constraint reservas_cancha_deporte_id_297a1b9e_fk_reservas_deporte_id
            references reservas_deporte
            deferrable initially deferred,
    superficie_id      bigint        not null
        constraint reservas_cancha_superficie_id_f8d8ca23_fk_reservas_
            references reservas_superficie
            deferrable initially deferred,
    constraint precio_luz_mayor_precio
        check (precio_luz >= precio)
);

alter table reservas_cancha
    owner to postgres;

create index reservas_cancha_club_id_faf63c6d
    on reservas_cancha (club_id);

create index reservas_cancha_deporte_id_297a1b9e
    on reservas_cancha (deporte_id);

create index reservas_cancha_superficie_id_f8d8ca23
    on reservas_cancha (superficie_id);

create table reservas_reserva
(
    is_deleted    boolean                  not null,
    deleted_at    timestamp with time zone,
    id            uuid                     not null
        primary key,
    nombre        varchar(50)              not null,
    email         varchar(254)             not null,
    fecha         date                     not null,
    hora          time                     not null,
    nota          text,
    precio        numeric(10, 2)           not null
        constraint precio_positivo
            check (precio >= (0)::numeric),
    con_luz       boolean                  not null,
    expira        boolean                  not null,
    forma_pago    smallint                 not null
        constraint reservas_reserva_forma_pago_check
            check (forma_pago >= 0),
    pagado        boolean                  not null,
    preference_id varchar(255),
    asistencia    boolean                  not null,
    created_at    timestamp with time zone not null,
    updated_at    timestamp with time zone not null,
    cancha_id     bigint                   not null
        constraint reservas_reserva_cancha_id_c34694dd_fk_reservas_cancha_id
            references reservas_cancha
            deferrable initially deferred,
    constraint asistencia_pagado
        check (NOT (asistencia AND (NOT pagado)))
);

alter table reservas_reserva
    owner to postgres;

create unique index reserva_unico
    on reservas_reserva (cancha_id, fecha, hora)
    where (NOT is_deleted);

create index reservas_reserva_cancha_id_c34694dd
    on reservas_reserva (cancha_id);

create table reservas_pagoreserva
(
    id                 bigint generated by default as identity
        primary key,
    payment_id         varchar(255)             not null,
    date_created       timestamp with time zone not null,
    date_approved      timestamp with time zone not null,
    status             varchar(50)              not null,
    status_detail      varchar(255)             not null,
    transaction_amount numeric(10, 2)           not null,
    reserva_id         uuid                     not null
        unique
        constraint reservas_pagoreserva_reserva_id_8b957cb1_fk_reservas_reserva_id
            references reservas_reserva
            deferrable initially deferred,
    date_updated       timestamp with time zone not null
);

alter table reservas_pagoreserva
    owner to postgres;

create table reservas_canchahoralaboral
(
    id              bigint generated by default as identity
        primary key,
    con_luz         boolean not null,
    cancha_id       bigint  not null
        constraint reservas_canchahoral_cancha_id_cf2e2221_fk_reservas_
            references reservas_cancha
            deferrable initially deferred,
    hora_laboral_id bigint  not null
        constraint reservas_canchahoral_hora_laboral_id_f2e3c9ab_fk_reservas_
            references reservas_horalaboral
            deferrable initially deferred,
    constraint reservas_canchahoralabor_cancha_id_hora_laboral_i_06f4af50_uniq
        unique (cancha_id, hora_laboral_id)
);

alter table reservas_canchahoralaboral
    owner to postgres;

create index reservas_canchahoralaboral_cancha_id_cf2e2221
    on reservas_canchahoralaboral (cancha_id);

create index reservas_canchahoralaboral_hora_laboral_id_f2e3c9ab
    on reservas_canchahoralaboral (hora_laboral_id);

create index reservas_superficie_nombre_165b7fa8_like
    on reservas_superficie (nombre varchar_pattern_ops);

create table reservas_parameters
(
    id                         bigint generated by default as identity
        primary key,
    horas_anticipacion         smallint not null
        constraint reservas_parameters_horas_anticipacion_check
            check (horas_anticipacion >= 0),
    max_reservas_user          smallint not null
        constraint reservas_parameters_max_reservas_user_check
            check (max_reservas_user >= 0),
    avisar_cancha_libre        boolean  not null,
    horas_avisar_cancha_libre  smallint not null
        constraint reservas_parameters_horas_avisar_cancha_libre_check
            check (horas_avisar_cancha_libre >= 0),
    finalizar_al_comenzar      boolean  not null,
    club_id                    bigint   not null
        unique
        constraint reservas_parameters_club_id_ed7bbffc_fk_core_club_id
            references core_club
            deferrable initially deferred,
    minutos_expiracion_reserva smallint not null
        constraint reservas_parameters_minutos_expiracion_reserva_check
            check (minutos_expiracion_reserva >= 0)
);

alter table reservas_parameters
    owner to postgres;

create table django_session
(
    session_key  varchar(40)              not null
        primary key,
    session_data text                     not null,
    expire_date  timestamp with time zone not null
);

alter table django_session
    owner to postgres;

create index django_session_session_key_c0390e0f_like
    on django_session (session_key varchar_pattern_ops);

create index django_session_expire_date_a5c62663
    on django_session (expire_date);

create table socios_categoria
(
    id          bigint generated by default as identity
        primary key,
    nombre      varchar(255)   not null,
    cuota       numeric(10, 2) not null
        constraint cuota_mayor_igual_cero
            check (cuota >= (0)::numeric),
    edad_minima smallint       not null
        constraint socios_categoria_edad_minima_check
            check (edad_minima >= 0),
    edad_maxima smallint       not null
        constraint socios_categoria_edad_maxima_check
            check (edad_maxima >= 0),
    constraint socios_categoria_edad_minima_edad_maxima_7ebfbc3d_uniq
        unique (edad_minima, edad_maxima)
);

alter table socios_categoria
    owner to postgres;

create table socios_cuotasocial
(
    id                bigint generated by default as identity
        primary key,
    is_deleted        boolean                  not null,
    deleted_at        timestamp with time zone,
    fecha_emision     timestamp with time zone not null,
    fecha_vencimiento timestamp with time zone,
    periodo_mes       smallint                 not null
        constraint socios_cuotasocial_periodo_mes_check
            check (periodo_mes >= 0),
    periodo_anio      integer                  not null
        constraint socios_cuotasocial_periodo_anio_check
            check (periodo_anio >= 0),
    total             numeric(10, 2)           not null
        constraint cuota_social_total_valido
            check (total >= (0)::numeric),
    cargo_extra       numeric(10, 2)           not null
        constraint cuota_social_cargo_extra_valido
            check (cargo_extra >= (0)::numeric),
    observaciones     text,
    persona_id        bigint                   not null
        constraint socios_cuotasocial_persona_id_baad1e4d_fk_accounts_persona_id
            references accounts_persona
            deferrable initially deferred,
    constraint socios_cuotasocial_persona_id_periodo_mes_p_d7c0c1d4_uniq
        unique (persona_id, periodo_mes, periodo_anio)
);

alter table socios_cuotasocial
    owner to postgres;

create index socios_cuotasocial_persona_id_baad1e4d
    on socios_cuotasocial (persona_id);

create table socios_socio
(
    id            bigint generated by default as identity
        primary key,
    is_deleted    boolean not null,
    deleted_at    timestamp with time zone,
    fecha_ingreso date    not null,
    persona_id    bigint  not null
        unique
        constraint socios_socio_persona_id_b787b51a_fk_accounts_persona_id
            references accounts_persona
            deferrable initially deferred,
    user_id       bigint
        unique
        constraint socios_socio_user_id_7f87fadd_fk_accounts_user_id
            references accounts_user
            deferrable initially deferred
);

alter table socios_socio
    owner to postgres;

create table socios_pagocuotasocial
(
    id              bigint generated by default as identity
        primary key,
    is_deleted      boolean        not null,
    deleted_at      timestamp with time zone,
    fecha_pago      date           not null,
    total_pagado    numeric(10, 2) not null
        constraint pago_cuota_social_total_pagado_valido
            check (total_pagado >= (0)::numeric),
    cuota_social_id bigint         not null
        unique
        constraint socios_pagocuotasoci_cuota_social_id_ef1fa30c_fk_socios_cu
            references socios_cuotasocial
            deferrable initially deferred,
    medio_pago_id   bigint         not null
        constraint socios_pagocuotasoci_medio_pago_id_4b481817_fk_parameter
            references parameters_mediopago
            deferrable initially deferred
);

alter table socios_pagocuotasocial
    owner to postgres;

create index socios_pagocuotasocial_medio_pago_id_4b481817
    on socios_pagocuotasocial (medio_pago_id);

create table socios_historicalsocio
(
    id                    bigint                   not null,
    is_deleted            boolean                  not null,
    deleted_at            timestamp with time zone,
    fecha_ingreso         date                     not null,
    history_id            integer generated by default as identity
        primary key,
    history_date          timestamp with time zone not null,
    history_change_reason varchar(100),
    history_type          varchar(1)               not null,
    history_user_id       bigint
        constraint socios_historicalsoc_history_user_id_5887f066_fk_accounts_
            references accounts_user
            deferrable initially deferred,
    persona_id            bigint,
    user_id               bigint
);

alter table socios_historicalsocio
    owner to postgres;

create index socios_historicalsocio_id_6b2af44d
    on socios_historicalsocio (id);

create index socios_historicalsocio_history_date_dae81ced
    on socios_historicalsocio (history_date);

create index socios_historicalsocio_history_user_id_5887f066
    on socios_historicalsocio (history_user_id);

create index socios_historicalsocio_persona_id_b3a16123
    on socios_historicalsocio (persona_id);

create index socios_historicalsocio_user_id_186e5920
    on socios_historicalsocio (user_id);

create table socios_historicalcuotasocial
(
    id                    bigint                   not null,
    is_deleted            boolean                  not null,
    deleted_at            timestamp with time zone,
    fecha_emision         timestamp with time zone not null,
    fecha_vencimiento     timestamp with time zone,
    periodo_mes           smallint                 not null
        constraint socios_historicalcuotasocial_periodo_mes_check
            check (periodo_mes >= 0),
    periodo_anio          integer                  not null
        constraint socios_historicalcuotasocial_periodo_anio_check
            check (periodo_anio >= 0),
    total                 numeric(10, 2)           not null,
    cargo_extra           numeric(10, 2)           not null,
    observaciones         text,
    history_id            integer generated by default as identity
        primary key,
    history_date          timestamp with time zone not null,
    history_change_reason varchar(100),
    history_type          varchar(1)               not null,
    history_user_id       bigint
        constraint socios_historicalcuo_history_user_id_e3415a07_fk_accounts_
            references accounts_user
            deferrable initially deferred,
    persona_id            bigint
);

alter table socios_historicalcuotasocial
    owner to postgres;

create index socios_historicalcuotasocial_id_115d8788
    on socios_historicalcuotasocial (id);

create index socios_historicalcuotasocial_history_date_6f552732
    on socios_historicalcuotasocial (history_date);

create index socios_historicalcuotasocial_history_user_id_e3415a07
    on socios_historicalcuotasocial (history_user_id);

create index socios_historicalcuotasocial_persona_id_42f60b72
    on socios_historicalcuotasocial (persona_id);

create table socios_itemcuotasocial
(
    id              bigint generated by default as identity
        primary key,
    nombre_completo varchar(100)   not null,
    categoria       varchar(50)    not null,
    cuota           numeric(10, 2) not null
        constraint detalle_cuota_social_cuota_valida
            check (cuota >= (0)::numeric),
    cargo_extra     numeric(10, 2) not null
        constraint detalle_cuota_social_cargo_extra_valido
            check (cargo_extra >= (0)::numeric),
    total_parcial   numeric(10, 2) not null
        constraint detalle_cuota_social_total_parcial_valido
            check (total_parcial >= (0)::numeric),
    cuota_social_id bigint         not null
        constraint socios_itemcuotasoci_cuota_social_id_dcea9d23_fk_socios_cu
            references socios_cuotasocial
            deferrable initially deferred,
    socio_id        bigint         not null
        constraint socios_itemcuotasocial_socio_id_1ce47af4_fk_socios_socio_id
            references socios_socio
            deferrable initially deferred
);

alter table socios_itemcuotasocial
    owner to postgres;

create index socios_itemcuotasocial_cuota_social_id_dcea9d23
    on socios_itemcuotasocial (cuota_social_id);

create index socios_itemcuotasocial_socio_id_1ce47af4
    on socios_itemcuotasocial (socio_id);

create table socios_parameters
(
    id                                bigint generated by default as identity
        primary key,
    edad_minima_titular               smallint      not null
        constraint socios_parameters_edad_minima_titular_check
            check (edad_minima_titular >= 0),
    dia_emision_cuota                 smallint      not null
        constraint socios_parameters_dia_emision_cuota_check
            check (dia_emision_cuota >= 0),
    dia_vencimiento_cuota             smallint      not null
        constraint socios_parameters_dia_vencimiento_cuota_check
            check (dia_vencimiento_cuota >= 0),
    cantidad_maxima_cuotas_pendientes smallint      not null
        constraint socios_parameters_cantidad_maxima_cuotas_pendientes_check
            check (cantidad_maxima_cuotas_pendientes >= 0),
    aumento_por_cuota_vencida         numeric(5, 2) not null,
    club_id                           bigint        not null
        unique
        constraint socios_parameters_club_id_b630abfa_fk_core_club_id
            references core_club
            deferrable initially deferred
);

alter table socios_parameters
    owner to postgres;

create table eventos_pagoventaticket
(
    id                 bigint generated by default as identity
        primary key,
    payment_id         varchar(255)             not null,
    status             varchar(50)              not null,
    status_detail      varchar(255)             not null,
    transaction_amount numeric(10, 2)           not null,
    date_created       timestamp with time zone not null,
    date_updated       timestamp with time zone not null,
    venta_ticket_id    bigint                   not null
        unique
        constraint eventos_pagoventatic_venta_ticket_id_0b6f10fa_fk_eventos_v
            references eventos_ventaticket
            deferrable initially deferred,
    date_approved      timestamp with time zone not null
);

alter table eventos_pagoventaticket
    owner to postgres;

create table eventos_parameters
(
    id                       bigint generated by default as identity
        primary key,
    minutos_expiracion_venta smallint not null
        constraint eventos_parameters_minutos_expiracion_venta_check
            check (minutos_expiracion_venta >= 0),
    club_id                  bigint   not null
        unique
        constraint eventos_parameters_club_id_ae47ae96_fk_core_club_id
            references core_club
            deferrable initially deferred,
    max_tickets_por_venta    smallint not null
        constraint eventos_parameters_max_tickets_por_venta_check
            check (max_tickets_por_venta >= 0)
);

alter table eventos_parameters
    owner to postgres;

create table django_site
(
    id     integer generated by default as identity
        primary key,
    domain varchar(100) not null
        constraint django_site_domain_a2e37b91_uniq
            unique,
    name   varchar(50)  not null
);

alter table django_site
    owner to postgres;

create index django_site_domain_a2e37b91_like
    on django_site (domain varchar_pattern_ops);

create table core_historicalclub
(
    id                    bigint                   not null,
    is_deleted            boolean                  not null,
    deleted_at            timestamp with time zone,
    nombre                varchar(255)             not null,
    direccion             varchar(255)             not null,
    email                 varchar(255)             not null,
    imagen                text,
    history_id            integer generated by default as identity
        primary key,
    history_date          timestamp with time zone not null,
    history_change_reason varchar(100),
    history_type          varchar(1)               not null,
    history_user_id       bigint
        constraint core_historicalclub_history_user_id_f2c9dc17_fk_accounts_
            references accounts_user
            deferrable initially deferred,
    localidad_id          bigint
);

alter table core_historicalclub
    owner to postgres;

create index core_historicalclub_id_5b335b74
    on core_historicalclub (id);

create index core_historicalclub_history_date_9312423e
    on core_historicalclub (history_date);

create index core_historicalclub_history_user_id_f2c9dc17
    on core_historicalclub (history_user_id);

create index core_historicalclub_localidad_id_33dc41b6
    on core_historicalclub (localidad_id);

create table eventos_historicalventaticket
(
    id                    bigint                   not null,
    is_deleted            boolean                  not null,
    deleted_at            timestamp with time zone,
    email                 varchar(254)             not null,
    total                 numeric(10, 2)           not null,
    pagado                boolean                  not null,
    preference_id         varchar(255),
    date_created          timestamp with time zone not null,
    date_updated          timestamp with time zone not null,
    history_id            integer generated by default as identity
        primary key,
    history_date          timestamp with time zone not null,
    history_change_reason varchar(100),
    history_type          varchar(1)               not null,
    evento_id             bigint,
    history_user_id       bigint
        constraint eventos_historicalve_history_user_id_c859512a_fk_accounts_
            references accounts_user
            deferrable initially deferred
);

alter table eventos_historicalventaticket
    owner to postgres;

create index eventos_historicalventaticket_id_b8f01483
    on eventos_historicalventaticket (id);

create index eventos_historicalventaticket_history_date_72b13e96
    on eventos_historicalventaticket (history_date);

create index eventos_historicalventaticket_evento_id_edbde790
    on eventos_historicalventaticket (evento_id);

create index eventos_historicalventaticket_history_user_id_c859512a
    on eventos_historicalventaticket (history_user_id);

create table eventos_historicalticketvariante
(
    id                    bigint                   not null,
    is_deleted            boolean                  not null,
    deleted_at            timestamp with time zone,
    nombre                varchar(255)             not null,
    precio                numeric(10, 2)           not null,
    total_tickets         integer                  not null
        constraint eventos_historicalticketvariante_total_tickets_check
            check (total_tickets >= 0),
    date_created          timestamp with time zone not null,
    date_updated          timestamp with time zone not null,
    history_id            integer generated by default as identity
        primary key,
    history_date          timestamp with time zone not null,
    history_change_reason varchar(100),
    history_type          varchar(1)               not null,
    evento_id             bigint,
    history_user_id       bigint
        constraint eventos_historicalti_history_user_id_2e371c5e_fk_accounts_
            references accounts_user
            deferrable initially deferred
);

alter table eventos_historicalticketvariante
    owner to postgres;

create index eventos_historicalticketvariante_id_fe3b3173
    on eventos_historicalticketvariante (id);

create index eventos_historicalticketvariante_history_date_bcbac424
    on eventos_historicalticketvariante (history_date);

create index eventos_historicalticketvariante_evento_id_f27ecdfb
    on eventos_historicalticketvariante (evento_id);

create index eventos_historicalticketvariante_history_user_id_2e371c5e
    on eventos_historicalticketvariante (history_user_id);

create table eventos_historicalticket
(
    id                    bigint                   not null,
    is_deleted            boolean                  not null,
    deleted_at            timestamp with time zone,
    nombre                varchar(255)             not null,
    is_used               boolean                  not null,
    check_date            timestamp with time zone,
    date_created          timestamp with time zone not null,
    date_updated          timestamp with time zone not null,
    history_id            integer generated by default as identity
        primary key,
    history_date          timestamp with time zone not null,
    history_change_reason varchar(100),
    history_type          varchar(1)               not null,
    check_by_id           bigint,
    history_user_id       bigint
        constraint eventos_historicalti_history_user_id_02273695_fk_accounts_
            references accounts_user
            deferrable initially deferred,
    ticket_variante_id    bigint,
    venta_ticket_id       bigint
);

alter table eventos_historicalticket
    owner to postgres;

create index eventos_historicalticket_id_4512a3f1
    on eventos_historicalticket (id);

create index eventos_historicalticket_history_date_1c9f294d
    on eventos_historicalticket (history_date);

create index eventos_historicalticket_check_by_id_65ae3c17
    on eventos_historicalticket (check_by_id);

create index eventos_historicalticket_history_user_id_02273695
    on eventos_historicalticket (history_user_id);

create index eventos_historicalticket_ticket_variante_id_04a8fac3
    on eventos_historicalticket (ticket_variante_id);

create index eventos_historicalticket_venta_ticket_id_3710c7f8
    on eventos_historicalticket (venta_ticket_id);

create table eventos_historicalparameters
(
    id                       bigint                   not null,
    minutos_expiracion_venta smallint                 not null
        constraint eventos_historicalparameters_minutos_expiracion_venta_check
            check (minutos_expiracion_venta >= 0),
    max_tickets_por_venta    smallint                 not null
        constraint eventos_historicalparameters_max_tickets_por_venta_check
            check (max_tickets_por_venta >= 0),
    history_id               integer generated by default as identity
        primary key,
    history_date             timestamp with time zone not null,
    history_change_reason    varchar(100),
    history_type             varchar(1)               not null,
    club_id                  bigint,
    history_user_id          bigint
        constraint eventos_historicalpa_history_user_id_f34c1193_fk_accounts_
            references accounts_user
            deferrable initially deferred
);

alter table eventos_historicalparameters
    owner to postgres;

create index eventos_historicalparameters_id_d04daaab
    on eventos_historicalparameters (id);

create index eventos_historicalparameters_history_date_6e2609ad
    on eventos_historicalparameters (history_date);

create index eventos_historicalparameters_club_id_9de0d80b
    on eventos_historicalparameters (club_id);

create index eventos_historicalparameters_history_user_id_f34c1193
    on eventos_historicalparameters (history_user_id);

create table eventos_historicalpagoventaticket
(
    id                    bigint                   not null,
    payment_id            varchar(255)             not null,
    status                varchar(50)              not null,
    status_detail         varchar(255)             not null,
    transaction_amount    numeric(10, 2)           not null,
    date_created          timestamp with time zone not null,
    date_updated          timestamp with time zone not null,
    date_approved         timestamp with time zone not null,
    history_id            integer generated by default as identity
        primary key,
    history_date          timestamp with time zone not null,
    history_change_reason varchar(100),
    history_type          varchar(1)               not null,
    history_user_id       bigint
        constraint eventos_historicalpa_history_user_id_4490fbdd_fk_accounts_
            references accounts_user
            deferrable initially deferred,
    venta_ticket_id       bigint
);

alter table eventos_historicalpagoventaticket
    owner to postgres;

create index eventos_historicalpagoventaticket_id_5ce5870c
    on eventos_historicalpagoventaticket (id);

create index eventos_historicalpagoventaticket_history_date_cfeb1cb2
    on eventos_historicalpagoventaticket (history_date);

create index eventos_historicalpagoventaticket_history_user_id_4490fbdd
    on eventos_historicalpagoventaticket (history_user_id);

create index eventos_historicalpagoventaticket_venta_ticket_id_3b25c844
    on eventos_historicalpagoventaticket (venta_ticket_id);

create table eventos_historicalitemventaticket
(
    id                    bigint                   not null,
    cantidad              integer                  not null
        constraint eventos_historicalitemventaticket_cantidad_check
            check (cantidad >= 0),
    subtotal              numeric(10, 2)           not null,
    history_id            integer generated by default as identity
        primary key,
    history_date          timestamp with time zone not null,
    history_change_reason varchar(100),
    history_type          varchar(1)               not null,
    history_user_id       bigint
        constraint eventos_historicalit_history_user_id_a67f8734_fk_accounts_
            references accounts_user
            deferrable initially deferred,
    ticket_variante_id    bigint,
    venta_ticket_id       bigint
);

alter table eventos_historicalitemventaticket
    owner to postgres;

create index eventos_historicalitemventaticket_id_abaafa81
    on eventos_historicalitemventaticket (id);

create index eventos_historicalitemventaticket_history_date_d3b45871
    on eventos_historicalitemventaticket (history_date);

create index eventos_historicalitemventaticket_history_user_id_a67f8734
    on eventos_historicalitemventaticket (history_user_id);

create index eventos_historicalitemventaticket_ticket_variante_id_1c500cb4
    on eventos_historicalitemventaticket (ticket_variante_id);

create index eventos_historicalitemventaticket_venta_ticket_id_fd0227d6
    on eventos_historicalitemventaticket (venta_ticket_id);

create table eventos_historicalevento
(
    id                    bigint                   not null,
    is_deleted            boolean                  not null,
    deleted_at            timestamp with time zone,
    nombre                varchar(255)             not null,
    descripcion           text                     not null,
    fecha_inicio          date                     not null,
    hora_inicio           time                     not null,
    fecha_fin             date                     not null,
    hora_fin              time                     not null,
    registro_deadline     date,
    mayor_edad            boolean                  not null,
    date_created          timestamp with time zone not null,
    date_updated          timestamp with time zone not null,
    imagen                text                     not null,
    history_id            integer generated by default as identity
        primary key,
    history_date          timestamp with time zone not null,
    history_change_reason varchar(100),
    history_type          varchar(1)               not null,
    history_user_id       bigint
        constraint eventos_historicalev_history_user_id_ad53da73_fk_accounts_
            references accounts_user
            deferrable initially deferred
);

alter table eventos_historicalevento
    owner to postgres;

create index eventos_historicalevento_id_3063b2a1
    on eventos_historicalevento (id);

create index eventos_historicalevento_history_date_0dbee2bb
    on eventos_historicalevento (history_date);

create index eventos_historicalevento_history_user_id_ad53da73
    on eventos_historicalevento (history_user_id);

create table reservas_historicalparameters
(
    id                         bigint                   not null,
    horas_anticipacion         smallint                 not null
        constraint reservas_historicalparameters_horas_anticipacion_check
            check (horas_anticipacion >= 0),
    minutos_expiracion_reserva smallint                 not null
        constraint reservas_historicalparameters_minutos_expiracion_reserva_check
            check (minutos_expiracion_reserva >= 0),
    max_reservas_user          smallint                 not null
        constraint reservas_historicalparameters_max_reservas_user_check
            check (max_reservas_user >= 0),
    avisar_cancha_libre        boolean                  not null,
    horas_avisar_cancha_libre  smallint                 not null
        constraint reservas_historicalparameters_horas_avisar_cancha_libre_check
            check (horas_avisar_cancha_libre >= 0),
    finalizar_al_comenzar      boolean                  not null,
    history_id                 integer generated by default as identity
        primary key,
    history_date               timestamp with time zone not null,
    history_change_reason      varchar(100),
    history_type               varchar(1)               not null,
    club_id                    bigint,
    history_user_id            bigint
        constraint reservas_historicalp_history_user_id_a333eac6_fk_accounts_
            references accounts_user
            deferrable initially deferred
);

alter table reservas_historicalparameters
    owner to postgres;

create index reservas_historicalparameters_id_92f1ecd0
    on reservas_historicalparameters (id);

create index reservas_historicalparameters_history_date_a4404cbc
    on reservas_historicalparameters (history_date);

create index reservas_historicalparameters_club_id_b82f7877
    on reservas_historicalparameters (club_id);

create index reservas_historicalparameters_history_user_id_a333eac6
    on reservas_historicalparameters (history_user_id);

create table reservas_historicalpagoreserva
(
    id                    bigint                   not null,
    payment_id            varchar(255)             not null,
    status                varchar(50)              not null,
    status_detail         varchar(255)             not null,
    transaction_amount    numeric(10, 2)           not null,
    date_created          timestamp with time zone not null,
    date_updated          timestamp with time zone not null,
    date_approved         timestamp with time zone not null,
    history_id            integer generated by default as identity
        primary key,
    history_date          timestamp with time zone not null,
    history_change_reason varchar(100),
    history_type          varchar(1)               not null,
    history_user_id       bigint
        constraint reservas_historicalp_history_user_id_d343ac5a_fk_accounts_
            references accounts_user
            deferrable initially deferred,
    reserva_id            uuid
);

alter table reservas_historicalpagoreserva
    owner to postgres;

create index reservas_historicalpagoreserva_id_cbae0998
    on reservas_historicalpagoreserva (id);

create index reservas_historicalpagoreserva_history_date_4f09f01b
    on reservas_historicalpagoreserva (history_date);

create index reservas_historicalpagoreserva_history_user_id_d343ac5a
    on reservas_historicalpagoreserva (history_user_id);

create index reservas_historicalpagoreserva_reserva_id_9ff35fe3
    on reservas_historicalpagoreserva (reserva_id);

create table reservas_historicalcancha
(
    id                    bigint                   not null,
    is_deleted            boolean                  not null,
    deleted_at            timestamp with time zone,
    cantidad_jugadores    smallint
        constraint reservas_historicalcancha_cantidad_jugadores_check
            check (cantidad_jugadores >= 0),
    precio                numeric(6, 2)            not null,
    precio_luz            numeric(6, 2),
    imagen                text,
    history_id            integer generated by default as identity
        primary key,
    history_date          timestamp with time zone not null,
    history_change_reason varchar(100),
    history_type          varchar(1)               not null,
    club_id               bigint,
    deporte_id            bigint,
    history_user_id       bigint
        constraint reservas_historicalc_history_user_id_38a40719_fk_accounts_
            references accounts_user
            deferrable initially deferred,
    superficie_id         bigint
);

alter table reservas_historicalcancha
    owner to postgres;

create index reservas_historicalcancha_id_9eccb90a
    on reservas_historicalcancha (id);

create index reservas_historicalcancha_history_date_06306658
    on reservas_historicalcancha (history_date);

create index reservas_historicalcancha_club_id_feafdca2
    on reservas_historicalcancha (club_id);

create index reservas_historicalcancha_deporte_id_d3e3f64a
    on reservas_historicalcancha (deporte_id);

create index reservas_historicalcancha_history_user_id_38a40719
    on reservas_historicalcancha (history_user_id);

create index reservas_historicalcancha_superficie_id_09ea099a
    on reservas_historicalcancha (superficie_id);


